name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.x'
        dotnet-quality: 'preview'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

    - name: Publish
      run: dotnet publish ./SamElhagPersonalSite/SamElhagPersonalSite.csproj --configuration Release --output ./publish

    - name: Stop IIS Site
      run: |
        Import-Module WebAdministration
        Stop-WebSite -Name "SamElhagPersonalSite"
      shell: powershell

    - name: Deploy to IIS
      run: |
        Copy-Item -Path "./publish/*" -Destination "C:\inetpub\wwwroot\SamElhagPersonalSite" -Recurse -Force
      shell: powershell

    - name: Start IIS Site
      run: |
        Import-Module WebAdministration
        Start-WebSite -Name "SamElhagPersonalSite"
      shell: powershell
